

export const SELECT_SUBREDDIT = 'SELECT_SUBREDDIT';
export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'